[build]
  # Directory with the frontend build output
  publish = "dist"
  # Build command to create the frontend
  command = "npm run build"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will need to be set in the Netlify dashboard
[build.environment]
  # Example: Point to your deployed backend API
  VITE_API_URL = "https://your-backend-url.herokuapp.com"

# Functions support if you want to use Netlify Functions for some backend logic
[functions]
  directory = "netlify/functions"