[build]
  # Directory with the frontend build output
  publish = "dist/public"
  # Build command to create the frontend build
  command = "npm run build"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions support if you want to use Netlify Functions as serverless backend
[functions]
  directory = "netlify/functions"
  # Increase function timeout for database operations
  node_bundler = "esbuild"

# Headers to enable PWA capabilities and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    
# Cache settings for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"