services:
  # Web Service for the LifeOS Application
  - type: web
    name: lifeos
    env: node
    plan: starter
    # Build configuration
    buildCommand: ./render-build.sh
    # Start command to run the application with custom startup script
    startCommand: ./render-start.sh
    # Automatic scaling configuration
    autoDeploy: true
    # Branch to deploy
    branch: main
    # Healthcheck path to ensure the service is running
    healthCheckPath: /api/diagnostic
    # Configure environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Do not sync with repo - set manually in Render dashboard
      - key: DEPLOYMENT_PLATFORM
        value: render
    # Routes configuration for the service
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      # Support Netlify-style paths for backward compatibility
      - type: rewrite
        source: /.netlify/functions/*
        destination: /api/$1

databases:
  # PostgreSQL Database for the application
  - name: lifeos-db
    plan: starter
    # Database type
    databaseName: lifeos
    # User configuration
    user: lifeos_user
    # IP allow list (empty means allow all)
    ipAllowList: []